name: CICD

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment"
        required: true
        type: choice

        options:
          - dev
          - stage
          - prod

jobs:

  code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        run: echo "Code cloned from GitHub"

  build:
    runs-on: ubuntu-latest
    needs: code

    steps:
      - name: Build Docker container
        run: echo "Docker container running"

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Testing the code
        run: echo "Code tested"

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Deploying the code
        run: echo "Deploying to ${{ inputs.environment }}"
